### ISSUE TITLE
Not work with magento 1.9.0.1

### ISSUE THREAD

**Issue by the-wanted** [Strategery-Inc/Magento-InfiniteScroll#101]
Hello,
i installed the extension in my magento 1.9.0.1 www.ladebora.it but the extension not work. when i go in a category i see the loading but not loading the items.
Can I resolve?
Best Regards

**Comment by janmyszkier** [comment]
Hello the-wanted, can you please give us some idea about your error? 
Maybe a url where you host your site?

**Comment by janmyszkier** [comment]
Hello the-wanted, can you please post the url to the category you see the error on?

**Comment by the-wanted** [comment]
Hello @janmyszkier this is the error

**Comment by janmyszkier** [comment]
@the-wanted 
I don't see any request to next/prev page on your page which means the most important part is missing.
Please:
a)
go to Admin -> System -> Cache Management -> Flush Cache Storage
and if the extension still won't work try:
b) Switch for a moment to base theme and confirm the extension has been installed correctly and work there (on rwd package)
Switching packages can be done on 
Admin -> System (top menu section) -> Configuration (top menu item) -> General (left menu section) -> Design(left menu item) ->Package (main section)

**Comment by the-wanted** [comment]
@janmyszkier 
1) i flushed the cache
2) i switched to base theme but the extension does not work

**Comment by janmyszkier** [comment]
@the-wanted : now that I look at it you are redirected to checkout/cart if you scroll down, and when I look into your code you indeed have .next link to checkout cart:
```
<a id="viewcart_button" href="http://www.ladebora.it/checkout/cart/" class="next"><span>Vai al carrello</span></a>
```
please try to change its class first and then check again

**Comment by the-wanted** [comment]
@janmyszkier in which file this issue is?

**Comment by janmyszkier** [comment]
@the-wanted: unfortunately I'm not sure, you have to search for yourself

just search your theme files for "viewcart_button" within the theme folder (app/design/frontend/default/galarainbow) and you'll surely find the file that you're looking for

**Comment by the-wanted** [comment]
@janmyszkier thanks i fix my issue
