### ISSUE TITLE
Load type based on viewport

### ISSUE THREAD

**Issue by stefkosmo** [Strategery-Inc/Magento-InfiniteScroll#102]
Hey, 

This is not an issue, but was wondering if it was possible to have load more button on desktop but automatic loading on phone and tablet?

thanks

**Comment by gabrielsomoza** [comment]
Yes, its possible, but since that's outside the scope of our plugin I'm afraid you'll have to have a developer customise it. We have developers available if you're interested: contact (at) strateger (dot) io

**Comment by stefkosmo** [comment]
Hey,

Thanks for your reply.

Here's an unrefined snippet to get this working:
<pre>
<code>
var viewport = function() {
      var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
      if (w < 767) {
            return 15;
      } else {
            return <?php echo (int) $helper->getConfigData('design/load_more_threshold') ?>
      }
}
</code>
</pre>

And then change:

<pre>
<code>
offset: viewport()
</code>
</pre>

Thanks

**Comment by gabrielsomoza** [comment]
Thanks for helping build our documentation with this snippet!
