### ISSUE TITLE
Extension not load more products of second page in magento 1.9.1

### ISSUE THREAD

**Issue by devangithakore** [Strategery-Inc/Magento-InfiniteScroll#103]
Hi,
I am using theme sns_tornto with magento. after installing this extension it shows loading circle but not load products of second page its shows me console error as below.
Error: Syntax error, unrecognized expression: {"status":"SUCCESS","viewpanel":"<div class=\"block block-layered-nav\">\n    <div class=\"block-title\">\n        <span>Shop By<\/span>\n    <\/div>\n    <div class=\"block-content\">\n                                    \n            <dl id=\"narrow-by-list\">\n                                                                                                    <dt>Price<\/dt>\n                    <dd>\n    \t\t\t\t\t\n\t\t\t\t<div class=\"price\">\n\t\t\t\t\t\n\t\t\t\t<div class=\"text-box\"><div class=\"inner\"><div class=\"price-from\">\n\t\t\t\t\t<span>$<\/span> <input type=\"text\" name=\"min\" id=\"minPrice\" class=\"priceTextBox\" value=\"12\"\/><\/div><div class=\"price-separator\">-<\/div><div class=\"price-to\"><span>$<\/span> <input type=\"text\" name=\"max\" id=\"maxPrice\" class=\"priceTextBox\" value=\"23\"\/><\/div>\n\t\t\t\t\t<\/div><input type=\"button\" value=\"Filter\" name=\"go\" class=\"go gfont\"\/>\n\t\t\t\t\t<input type=\"hidden\" id=\"amount\" readonly=\"readonly\" style=\"background:none; border:none;\" value=\"$12 - $23\" \/>\n\n\t\t\t\t<\/div>\n\t\t\t\t\t<div class=\"range-wrap\"><div id=\"slider-range\"><\/div><\/div>\n\n\t\t\t\t<\/div>\n\t\t\t<script type=\"text\/javascript\">\n\t\t\t\tjQuery(function($) {\n\t\t\t\t\tvar newMinPrice, newMaxPrice, url, temp;\n\t\t\t\t\tvar categoryMinPrice = 12;\n\t\t\t\t\tvar categoryMaxPrice = 23;\n\t\t\t\t\tfunction isNumber(n) {\n\t\t\t\t\t  return !isNaN(parseFloat(n)) && isFinite(n);\n\t\t\t\t\t}\n\n\t\t\t\t\t$(\".priceTextBox\").focus(function(){\n\t\t\t\t\t\ttemp = $(this).val();\n\t\t\t\t\t});\n\n\t\t\t\t\t$(\".priceTextBox\").keyup(function(){\n\t\t\t\t\t\tvar value = $(this).val();\n\t\t\t\t\t\tif(!isNumber(value)){\n\t\t\t\t\t\t\t$(this).val(temp);\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\t\t\t\t\t$(\".priceTextBox\").keypress(function(e){\n\t\t\t\t\t\tif(e.keyCode == 13){\n\t\t\t\t\t\t\tvar value = $(this).val();\n\t\t\t\t\t\t\tif(value < categoryMinPrice || value > categoryMaxPrice){\n\t\t\t\t\t\t\t\t$(this).val(temp);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\turl = getUrl($(\"#minPrice\").val(), $(\"#maxPrice\").val());\n\t\t\t\t\t\t\tajaxFilter(url);\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\t\t\t\t\t$(\".priceTextBox\").blur(function(){\n\t\t\t\t\t\tvar value = $(this).val();\n\t\t\t\t\t\tif(value < categoryMinPrice || value > categoryMaxPrice){\n\t\t\t\t\t\t\t$(this).val(temp);\n\t\t\t\t\t\t}\n\n\t\t\t\t\t});\n\n\t\t\t\t\t$(\".go\").click(function(){\n\t\t\t\t\t\turl = getUrl($(\"#minPrice\").val(), $(\"#maxPrice\").val());\n\t\t\t\t\t\tajaxFilter(url);\n\t\t\t\t\t});\n\n\t\t\t\t\t$( \"#slider-range\" ).slider({\n\t\t\t\t\t\trange: true,\n\t\t\t\t\t\tmin: categoryMinPrice,\n\t\t\t\t\t\tmax: categoryMaxPrice,\n\t\t\t\t\t\tvalues: [ 12, 23 ],\n\t\t\t\t\t\tslide: function( event, ui ) {\n\t\t\t\t\t\t\tnewMinPrice = ui.values[0];\n\t\t\t\t\t\t\tnewMaxPrice = ui.values[1];\n\n\t\t\t\t\t\t\t$( \"#amount\" ).val( \"$\" + newMinPrice + \" - $\" + newMaxPrice );\n\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\/\/ Update TextBox Price\n\t\t\t\t\t\t\t$(\"#minPrice\").val(newMinPrice); \n\t\t\t\t\t\t\t$(\"#maxPrice\").val(newMaxPrice);\n\n\t\t\t\t\t\t},stop: function( event, ui ) {\n\n\t\t\t\t\t\t\t\/\/ Current Min and Max Price\n\t\t\t\t\t\t\tvar newMinPrice = ui.values[0];\n\t\t\t\t\t\t\tvar newMaxPrice = ui.values[1];\n\n\t\t\t\t\t\t\t\/\/ Update Text Price\n\t\t\t\t\t\t\t$( \"#amount\" ).val( \"$\"+newMinPrice+\" - $\"+newMaxPrice );\n\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\/\/ Update TextBox Price\n\t\t\t\t\t\t\t$(\"#minPrice\").val(newMinPrice); \n\t\t\t\t\t\t\t$(\"#maxPrice\").val(newMaxPrice);\n\n\t\t\t\t\t\t\turl = getUrl(newMinPrice,newMaxPrice);\n\t\t\t\t\t\t\tif(newMinPrice != 12 && newMaxPrice != 23){\n\t\t\t\t\t\t\t\tclearTimeout(timer);\n\t\t\t\t\t\t\t\t\/\/window.location= url;\n\n\t\t\t\t\t\t\t}else{\n\t\t\t\t\t\t\t\t\ttimer = setTimeout(function(){\n\t\t\t\t\t\t\t\t\t\tajaxFilter(url);\n\t\t\t\t\t\t\t\t\t}, 200);\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\t\t\t\t\tfunction getUrl(newMinPrice, newMaxPrice){\n\t\t\t\t\t\treturn \"http:\/\/localhost\/magento\/index.php\/test1.html\"+\"?min=\"+newMinPrice+\"&max=\"+newMaxPrice+\"&p=2\";\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t<\/script>\n\t\t    \t\t\t\t<\/dd>\n                                            <\/dl>\n            <script type=\"text\/javascript\">decorateDataList('narrow-by-list')<\/script>\n            <\/div>\n<\/div>\n","productlist":"<div class=\"category-products\">\n    <div class=\"toolbar clearfix\">\n        <div class=\"toolbar-inner\">\n                <p class=\"view-mode\">\n                                    <label>View as:<\/label>\n                                                <strong title=\"Grid\" class=\"icon-grid\"><\/strong>\n                                                                <a href=\"http:\/\/localhost\/magento\/index.php\/test1.html?mode=list\" title=\"List\" class=\"icon-list\"><\/a>\n                                                <\/p>\n                <div class=\"sort-by\">\n            <label>Sort By<\/label>\n            <div class=\"select-new\"><div class=\"select-inner\">\n            <select class=\"select-sort-by\" onchange=\"setLocation(this.value)\">\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=position\" selected=\"selected\">\n                    Position                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=name\">\n                    Name                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=price\">\n                    Price                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=color\">\n                    pink                <\/option>\n                        <\/select>\n            <\/div><\/div>\n                            <a class=\"set-desc\" href=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=desc&amp;order=position\" title=\"Set Descending Direction\"><\/a>\n                    <\/div>\n    \t<div class=\"limiter\">\n            <label>Show<\/label>\n            <div class=\"select-new\"><div class=\"select-inner\">\n            <select class=\"select-limit-show\" onchange=\"setLocation(this.value)\">\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=5\" selected=\"selected\">\n                    5                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=10\">\n                    10                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=15\">\n                    15                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=20\">\n                    20                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=25\">\n                    25                <\/option>\n                        <\/select><\/div><\/div> per page        <\/div>\n        <div class=\"pager\">\n            <p class=\"amount\">\n                                    Items 6 to 6 of 6 total                            <\/p>\n            \n    \n    \n    \n        <div class=\"pages\">\n        <strong>Page:<\/strong>\n        <ol>\n                    <li>\n                <a class=\"previous i-previous\" href=\"http:\/\/localhost\/magento\/index.php\/test1.html?p=1\" title=\"Previous\">\n                                            <img src=\"http:\/\/localhost\/magento\/skin\/frontend\/base\/default\/images\/pager_arrow_left.gif\" alt=\"Previous\" class=\"v-middle\" \/>\n                                    <\/a>\n            <\/li>\n        \n        \n        \n                                    <li><a href=\"http:\/\/localhost\/magento\/index.php\/test1.html?p=1\">1<\/a><\/li>\n                                                <li class=\"current\">2<\/li>\n                    \n\n        \n        \n                <\/ol>\n\n    <\/div>\n    \n    \n        <\/div>\n    <\/div>\n        \n<\/div>\n<script type=\"text\/javascript\" >\n    jQuery(function($){\n        \/\/ Transforming the form's Select control using jqTransform Plugin.\n        $(\".toolbar .limiter .select-new .select-inner\").jqTransform();\n        $(\".toolbar .sort-by .select-new .select-inner\").jqTransform();\n    });\n<\/script>\n        <div class=\"sns-products-container clearfix\">\n    \n        <div class=\"products-grid row style2\">\n                \t                \t            <div class=\"item col-md-6 col-sm-6 col-xs-12 col-md-first col-sm-first col-xs-first col-xs-last\">\n\t\t\t\t<div class=\"item-inner clearfix\">\n        \t\t\t<div class=\"badges\">\n                    \t                    <\/div>\n                \t<div class=\"item-img clearfix\">\n\t\t\t            <a href=\"http:\/\/localhost\/magento\/index.php\/test1\/test6.html\" title=\"test6\" class=\"product-image\">\n\t\t\t                <span class=\"image-main\">\n\t\t\t            \t<img src=\"http:\/\/localhost\/magento\/media\/catalog\/product\/cache\/1\/small_image\/170x190\/9df78eab33525d08d6e5fb8d27136e95\/images\/catalog\/product\/placeholder\/small_image.jpg\" alt=\"test6\" \/>\n\t\t\t                <\/span>\n\t\t\t            <\/a>\n\t                    \t                    <div class=\"quickview-wrap\">\n\t                        <a href=\"http:\/\/localhost\/magento\/index.php\/test1\/test6.html\" title=\"test6\" style=\"display:none\"><\/a>\n\t                    <\/div>\n\t                                        <\/div>\n                    <div class=\"item-info\">\n                        <div class=\"info-inner\">\n                            <div class=\"item-title\">\n                                <a href=\"http:\/\/localhost\/magento\/index.php\/test1\/test6.html\" title=\"test6\">\n                                    test6                                <\/a>\n                            <\/div>\n                            <div class=\"item-price\">\n                                \n\n                        \n    <div class=\"price-box\">\n                                                                <span class=\"regular-price\" id=\"product-price-24274821435215238\">\n                                            <span class=\"price\">$23.00<\/span>                                    <\/span>\n                        \n        <\/div>\n\n                            <\/div>\n                                <p class=\"no-rating\"><a href=\"http:\/\/localhost\/magento\/index.php\/review\/product\/list\/id\/24\/category\/4\/#review-form\">Be the first to review this product<\/a><\/p>\n                            <div class=\"actions\">\n    \t\t\t\t\t\t\t    \t\t\t\t\t\t\t        \t\t\t\t\t\t\t        <button title=\"Add to Cart\" class=\"btn-cart\" onclick=\"setLocation('http:\/\/localhost\/magento\/index.php\/checkout\/cart\/add\/uenc\/aHR0cDovL2xvY2FsaG9zdC9tYWdlbnRvL2luZGV4LnBocC90ZXN0MS5odG1sP3A9Mg,,\/product\/24\/form_key\/KKwReEfUYCtpHdSV\/')\" data-toggle=\"tooltip\" data-original-title=\"Add to Cart\"><\/button>\n    \t\t\t\t\t\t\t        \t\t\t\t\t\t\t                                <ul class=\"add-to-links\">\n                                                                            <li><a title=\"Add to Wishlist\" href=\"http:\/\/localhost\/magento\/index.php\/wishlist\/index\/add\/product\/24\/form_key\/KKwReEfUYCtpHdSV\/\" class=\"link-wishlist\" data-toggle=\"tooltip\" data-original-title=\"Add to Wishlist\"><\/a><\/li>\n                                                                                                                <li><a title=\"Add to Compare\" href=\"http:\/\/localhost\/magento\/index.php\/catalog\/product_compare\/add\/product\/24\/uenc\/aHR0cDovL2xvY2FsaG9zdC9tYWdlbnRvL2luZGV4LnBocC90ZXN0MS5odG1sP3A9Mg,,\/form_key\/KKwReEfUYCtpHdSV\/\" class=\"link-compare\" data-toggle=\"tooltip\" data-original-title=\"Add to Compare\"><\/a><\/li>\n                                                                    <\/ul>\n                            <\/div>\n                        <\/div>\n                    <\/div>\n\t\t\t\t<\/div>\n            <\/div>\n                <\/div>\n    \t<\/div>\n    <div class=\"toolbar-bottom clearfix\">\n        <div class=\"toolbar clearfix\">\n        <div class=\"toolbar-inner\">\n                <p class=\"view-mode\">\n                                    <label>View as:<\/label>\n                                                <strong title=\"Grid\" class=\"icon-grid\"><\/strong>\n                                                                <a href=\"http:\/\/localhost\/magento\/index.php\/test1.html?mode=list\" title=\"List\" class=\"icon-list\"><\/a>\n                                                <\/p>\n                <div class=\"sort-by\">\n            <label>Sort By<\/label>\n            <div class=\"select-new\"><div class=\"select-inner\">\n            <select class=\"select-sort-by\" onchange=\"setLocation(this.value)\">\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=position\" selected=\"selected\">\n                    Position                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=name\">\n                    Name                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=price\">\n                    Price                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=asc&amp;order=color\">\n                    pink                <\/option>\n                        <\/select>\n            <\/div><\/div>\n                            <a class=\"set-desc\" href=\"http:\/\/localhost\/magento\/index.php\/test1.html?dir=desc&amp;order=position\" title=\"Set Descending Direction\"><\/a>\n                    <\/div>\n    \t<div class=\"limiter\">\n            <label>Show<\/label>\n            <div class=\"select-new\"><div class=\"select-inner\">\n            <select class=\"select-limit-show\" onchange=\"setLocation(this.value)\">\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=5\" selected=\"selected\">\n                    5                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=10\">\n                    10                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=15\">\n                    15                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=20\">\n                    20                <\/option>\n                            <option value=\"http:\/\/localhost\/magento\/index.php\/test1.html?limit=25\">\n                    25                <\/option>\n                        <\/select><\/div><\/div> per page        <\/div>\n        <div class=\"pager\">\n            <p class=\"amount\">\n                                    Items 6 to 6 of 6 total                            <\/p>\n            \n    \n    \n    \n        <div class=\"pages\">\n        <strong>Page:<\/strong>\n        <ol>\n                    <li>\n                <a class=\"previous i-previous\" href=\"http:\/\/localhost\/magento\/index.php\/test1.html?p=1\" title=\"Previous\">\n                                            <img src=\"http:\/\/localhost\/magento\/skin\/frontend\/base\/default\/images\/pager_arrow_left.gif\" alt=\"Previous\" class=\"v-middle\" \/>\n                                    <\/a>\n            <\/li>\n        \n        \n        \n                                    <li><a href=\"http:\/\/localhost\/magento\/index.php\/test1.html?p=1\">1<\/a><\/li>\n                                                <li class=\"current\">2<\/li>\n                    \n\n        \n        \n                <\/ol>\n\n    <\/div>\n    \n    \n        <\/div>\n    <\/div>\n        \n<\/div>\n<script type=\"text\/javascript\" >\n    jQuery(function($){\n        \/\/ Transforming the form's Select control using jqTransform Plugin.\n        $(\".toolbar .limiter .select-new .select-inner\").jqTransform();\n        $(\".toolbar .sort-by .select-new .select-inner\").jqTransform();\n    });\n<\/script>\n    <\/div>\n    <script type=\"text\/javascript\">\n    \/\/<![CDATA[\n        jQuery(function($){\n        \/\/jQuery(document).ready(function($){\n            $('.jqTransformSelectWrapper ul li a').on('click',function(e){\n                var i=$(this).attr('index'); \/\/alert(i);\n                var wrap_ = $(this).parents('.jqTransformSelectWrapper'); \/\/alert($(wrap_).html());\n                j=0;\n                $(wrap_).find('option').each(function(){\n                    if(j==i){\n                        ajaxFilter($(this).attr('value'));\n                    }\n                    j++;\n                });\n                e.preventDefault();\n            });\n        });\n    \/\/]]>\n    <\/script>\n<\/div>\n\t\t\n\t\t\n\t\t\n\t\t\n\t\t\n\t\t\n\t\t\n"} please help me as soon as possible.
thanks,

**Comment by janmyszkier** [comment]
@devangithakore : can you please give us the URL you have it on?

**Comment by devangithakore** [comment]
hi,
I am on mine local server.so Cant give you url.

Thanks.
Devangi.

**Comment by janmyszkier** [comment]
is there a way we can set up a chrome remote desktop session for me to have a look? or can you send the theme files to us for debug?

**Comment by gabrielsomoza** [comment]
There's absolutely no way our extension can be generating that kind of response.

What you're experiencing is almost certainly this issue: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Nothing-Happens,-Although-the-%22Loading-Next-Page%22-Message-is-Visible

I recommend you identify the extension that's aggressively modifying AJAX responses and disable it. We can re-open this ticket if something else comes to light.

**Comment by devangithakore** [comment]
Hi,
     Can you help to if i will give you remote access to you on 
teamviewer10.

Thanks,
Devangi.

**Comment by gabrielsomoza** [comment]
Hi @devangithakore,

Since this is a free extension we can't provide free support for issues that are not caused by our extension. I'm afraid that includes remote assistance. If you'd like to hire one of our developers for an hour or two in order to help you fix this issue please email us at: contact (at) strategery (dot) io

Sorry I had to jump in last-moment to say this, but Jan is a new addition to our team so he didn't know this yet.

**Comment by devangithakore** [comment]
Hi,
ok.Can you just tell me is it working for magento1.9.1?it would be great 
help for me if you can say.
Thanks,
Devangi.

**Comment by gabrielsomoza** [comment]
Hi Devangi,

Yes, our extension has been confirmed to work with Magento 1.9.1 in dozens of other stores.

All best,
Gabriel
