### ISSUE TITLE
Scrolling is not working

### ISSUE THREAD

**Issue by esgopi88** [Strategery-Inc/Magento-InfiniteScroll#105]
Hi
     http://www.yourwebsite.com/infinitescroll2/js  if i give this link its giving 404 error page and i changed yourwebsite name with my website name.What i can do?to solve this problem.

**Comment by janmyszkier** [comment]
@esgopi88 : I believe you are referring to magento admin panel? Please make sure you:
1. Clear magento cache
2. log out of your admin account and log in again so you can refresh your admin access rules in your session.

This should fix your problem right away
