### ISSUE TITLE
Scrolling is not working

### ISSUE THREAD

**Issue by esgopi88** [Strategery-Inc/Magento-InfiniteScroll#106]
Hi 
    If i merge the JavaScript script files scrolling is not working what is the problem?how can i solve it

**Comment by janmyszkier** [comment]
@esgopi88 : I just checked this on most magento 1.9.1.1 and it works without problem. Can you please let me know on what version do you encounter the problem?
Most probably something else in your theme is not compatible with js merge functionality.

**Comment by damian-pastorini** [comment]
I'm not able to reproduce the issue.
@esgopi88 , could you give us more information to reproduce?

**Comment by damian-pastorini** [comment]
@esgopi88 we need more info to reproduce the issue. Thanks.
