### ISSUE TITLE
Confusing Version Numbers

### ISSUE THREAD

**Issue by jhoelzl** [Strategery-Inc/Magento-InfiniteScroll#110]
Hallo,

it would be nice if you could use the same version numbers in your etc/config.xml, Magento Connect and git release log. Currently, they are not the same, although the code is the same.

**Comment by janmyszkier** [comment]
@jhoelzl : can you please let me know which file do you have in mind?
as far as I see our [config.xml](https://github.com/Strategery-Inc/Magento-InfiniteScroll/blob/master/app/code/community/Strategery/Infinitescroll/etc/config.xml)

we already have correct versioning

**Comment by jhoelzl** [comment]
Of course! On http://www.magentocommerce.com/magento-connect/strategery-infinitescroll.html, you write version number 3.2.1, on  https://github.com/Strategery-Inc/Magento-InfiniteScroll/releases you write v2.0, although it should be 3.1.0 everywhere.

**Comment by janmyszkier** [comment]
@jhoelzl : Thanks for quick reply! 
I'll see with the others into resolving this soon and standarize both.
Thanks again for spotting this.

**Comment by gabrielsomoza** [comment]
@jhoelzl we haven't been making releases on Github because we don't use Composer with Magento ourselves, but you make a good point.

The Magento Connect page shows what the correct version number is. @janmyszkier could you update files to reflect that?

**Comment by damian-pastorini** [comment]
The last version in Connect is 3.3.0, 
Today we merged a few fixes and I also created this PR which includes a fix for the configurable swatches and a version update to 3.5.0:
https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/148
We will upload the last package to connect with version 3.5.0 to keep all the versions the same.
