### ISSUE TITLE
It doesn't seem to work with iPhones

### ISSUE THREAD

**Issue by onepack** [Strategery-Inc/Magento-InfiniteScroll#113]
A customer contacted me that the scroll is not functioning on her iPhone.
IPad, galaxy tab and htc phone don't seem to have issues.

**Comment by damian-pastorini** [comment]
Could you provide more info please? 
Do you have a custom theme installed? 
An URL where we can take a look?
Thanks!

**Comment by onepack** [comment]
You can check it at http://www.grovet.com
It's a custom theme built by me.

**Comment by janmyszkier** [comment]
@onepack : I just tested this on IPhone 6 and 5S, using instruments category, no issues on either.
Please provide steps to reproduce the issue.

**Comment by onepack** [comment]
Case closed as I did not hear from the client anymore.
