### ISSUE TITLE
Jquery Conflict issue with InfiniteScroll

### ISSUE THREAD

**Issue by satishsojitra** [Strategery-Inc/Magento-InfiniteScroll#114]
Hi I have used this extension in Magento Version 1.9.1.0. Initially in header one jquery-1.11.3.min.js is loading then from app\design\frontend\base\default\template\strategery\infinitescroll\init.phtml one jquery is loading ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js.

Now when two jquery is loading in same page in category list page then it's conflicting. I have removed jquery from the init.phtml then conflict is resolved but lazy load stopped working. If I add jquery in init.phtml then only lazy load is working.

What can be the solution ?

**Comment by janmyszkier** [comment]
@satishsojitra: Have you tried going to Admin -> System ->Configuration -> STRATEGERY -> InfiniteScroll -> General 
and setting "Include jQuery" to "No" ?

**Comment by satishsojitra** [comment]
Hi Janmyszkier

Yes I have tried that option too.

**Comment by janmyszkier** [comment]
I've tried the extension on 1.9.1.0 recently and I had no such issues, is this default theme you have problems with? if not, is there url we can see it at?

**Comment by satishsojitra** [comment]
We are using RWD theme. 
As we all know whenever two jquery load in page it will create problems and ideal solution for that to remove one. Whenever I am removing jquery from extension it's stopped working.
Can you please share your email id if possible ?

**Comment by janmyszkier** [comment]
@satishsojitra: unfortunately I can't share my direct address with you. 
However, If you'd like to hire one of our developers for an hour or two in order to help you fix this issue with your custom RWD theme, please email us at: contact (at) strategery (dot) io

**Comment by PawanKumarN** [comment]
I have same issues please help me how to resolve
