### ISSUE TITLE
There's no 'ready' event to hook into

### ISSUE THREAD

**Issue by stefbowerman** [Strategery-Inc/Magento-InfiniteScroll#115]
I would like to add some code based on different infinite scroll events that are fired however, I can't seem to figure out a way to hook into them.

I know it should be as simple as..

```
ias.on('event', function(){ ... });
```

but ```window.ias``` is created in a callback function in jQuery.getScript (which loads the ias script) which is in an inline script block.  There is no window event to let me know this function has resolved and that the variable is available.  

There are also no event hooks to pass in as options when creating the ias instance, so creating an ias_config.js file doesn't really do any good.

Am I missing something or do I have to do something really hacky to check if the variable exists?

**Comment by jasonalvis** [comment]
Hi @stefbowerman,

I also came across the same problem and I wasn't sure if I was missing something too.

In my view the ias_config.js file is completely useless for a few reasons:

1. The hooks don't seem to work and it just errors out
2. You can't use php in the JS file meaning you can't use the admin config settings for the text strings

Alternatively I scrapped the use of the ias_config.js file and went down the route of copying the file template/strategery/infinitescroll/init.phtml to my package/theme and changing the settings directly in there.

The hooks seem to work ok in here, example:

window.ias.on('rendered', function(items){
    var count = jQuery(".category-products").find(".product-item").length;

    // update the "showing x out of y" number in the toolbar
    jQuery(".js-ias-items").each(function(){
        jQuery(this).text(count);
    });

    SgyIAS._log({eventName: 'render', items: items});
});

Hope this helps, cheers.

**Comment by stefbowerman** [comment]
I will probably end up having to copy over a template and override what's already there.  It's too bad because there is already an 'event' but it only logs to a global variable and nothing more.
```
SgyIAS._log('Done loading IAS.');
```

Would it be too much to ask for a window event so we know when ias variables are available?  Something like..
```
jQuery('window').trigger('ias.ready');
```

**Comment by janmyszkier** [comment]
created a pull request covering this. 
https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/119

**Comment by damian-pastorini** [comment]
@stefbowerman , I'm closing this. You can also check our last comments in #139 and #140.
Best,
Damian
