### ISSUE TITLE
Showing previous pages when you've clicked the back button

### ISSUE THREAD

**Issue by jasonalvis** [Strategery-Inc/Magento-InfiniteScroll#116]
Hey all,

This issue is related to https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/93 whereby users cant view previous pages after clicking the back button, they can only go to the next pages.

I also came across this issue and I was stumped as the jQuery library it uses for the infinite scrolling found here http://infiniteajaxscroll.com/examples/history/page2.html has a history demo. In the demo it adds a "load previous items" (after you click the back button), which is just what I think is needed, so why isn't it working?

It was actually a simple fix in that the target class for the previous pagination link is wrong (if your working with the rwd theme anyway). The target class it looks for is "prev" however the class that is actually on the button is "previous".

Quick fix is to simply change the class on the previous button to "prev" or you could change the ias options to looks for "previous" - your call. (template/page/html/pager.phtml)

Now when you click the back button it will show the previous button at the top of the product list so the user has the option of viewing previous pages if they want to.

I think it's worth updating the code to make the default selector "previous" as I would have thought the majority of users are going down the rwd theme route and may also face this problem.

Thanks

Jason

**Comment by damian-pastorini** [comment]
Hi @jasonalvis , thanks for your recommendations!
I just updated the jQuery IAS library, fixed the previous class configuration and added some system-configurations for future modifications.
@gsomoza I just created this PR: https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/149
We should include those fixes in our next release for Connect too (3.5.0).

**Comment by damian-pastorini** [comment]
Merged PR, closing issue.
