### ISSUE TITLE
it seems your modman has some wrong source paths

### ISSUE THREAD

**Issue by cojaco** [Strategery-Inc/Magento-InfiniteScroll#120]
app/design/frontend/default/default/layout/*.xml app/design/frontend/base/default/layout/
app/design/frontend/default/default/template/strategery/* app/design/frontend/base/default/template/strategery/

the path app/design/frontend/default/default/ does not exist in your repro

**Comment by gabrielsomoza** [comment]
We have a PR for that: https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/118 - just need to get it tested properly before merging.

**Comment by damian-pastorini** [comment]
Merged the fix #118 , I tested and it's working fine now but you will probably need to run a modman update to fix the extension.
