### ISSUE TITLE
Mage Registry Error

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/Magento-InfiniteScroll#121]
From Magento Connect:
 
I receive the following error when trying to log in to Magento Back Office after installtion.
 
Mage registry key "_singleton/infinitescroll/observer" already exists

On Magento 1.9.1

**Comment by somshine** [comment]
a:5:{i:0;s:69:"Mage registry key "_singleton/infinitescroll/observer" already exists";i:1;s:1475:"#0 /home/comfyhou/public_html/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /home/comfyhou/public_html/app/Mage.php(477): Mage::register('_singleton/infi...', false)
#2 /home/comfyhou/public_html/includes/src/__default.php(22026): Mage::getSingleton('infinitescroll/...')
#3 /home/comfyhou/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#4 /home/comfyhou/public_html/includes/src/__default.php(14361): Mage::dispatchEvent('controller_acti...', Array)
#5 /home/comfyhou/public_html/includes/src/Mage_Adminhtml_Controller_Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#6 /home/comfyhou/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(51): Mage_Adminhtml_Controller_Action->preDispatch()
#7 /home/comfyhou/public_html/includes/src/__default.php(14241): Mage_Adminhtml_System_ConfigController->preDispatch()
#8 /home/comfyhou/public_html/includes/src/__default.php(18698): Mage_Core_Controller_Varien_Action->dispatch('edit')
#9 /home/comfyhou/public_html/includes/src/__default.php(18228): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/comfyhou/public_html/includes/src/__default.php(21056): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/comfyhou/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /home/comfyhou/public_html/index.php(83): Mage::run('', 'store')
#13 {main}";s:3:"url";s:74:"/index.php/admin/system_config/index/key/5ff78bec77125d3acddb1491fa731e64/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by damian-pastorini** [comment]
I'm not able to reproduce this.
