### ISSUE TITLE
Loads the same page over and over again

### ISSUE THREAD

**Issue by Rallendk** [Strategery-Inc/Magento-InfiniteScroll#125]
Hey there.

For some reason my page loads the first page over and over again when using this Infinitescroll. I am pretty sure I have used the right selector for next (.next)

**Comment by zeki893** [comment]
have you checked the wiki?
https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/InfiniteScroll-is-loading-always-the-same-page
