### ISSUE TITLE
Are you planning to port to Magento 2 ?

### ISSUE THREAD

**Issue by pantaoran** [Strategery-Inc/Magento-InfiniteScroll#135]
I'm wondering if you guys are going to offer this module for Magento 2 in the future, and if yes, when?

**Comment by gabrielsomoza** [comment]
Yes, we are but we don't have a timeline right now. Hopefully we can do it at some point during Q2 2016.

**Comment by damian-pastorini** [comment]
We started a Magento 2 implementation in the "magento_2" branch: 
https://github.com/Strategery-Inc/Magento-InfiniteScroll/tree/magento2
We are still working on it but if you like to try it the code in the branch already works.

**Comment by pjona** [comment]
@damian-pastorini: I tried with Magento 2.0.6 and everything works out of the box. Thanks.

**Comment by damian-pastorini** [comment]
Nice to hear that @pjona , we are still working on the extension for now we just port it to M2, but we are planning to do a big M2 way reactor on it.
I'll let you know as soon we have the new version ready.

**Comment by damian-pastorini** [comment]
@pjona I started with the extesion refactoring, we created a new repo for it:
https://github.com/Strategery-Inc/Magento2-InfiniteScroll
I'll close this ticket now, please make sure for follow up on the new repo.
Best!
