### ISSUE TITLE
product loader is very slow

### ISSUE THREAD

**Issue by sunny29mca** [Strategery-Inc/Magento-InfiniteScroll#143]
We are using this ext but found it takes much time to load product

please help to resolve this.

http://tradetodayonline.com/men.html

**Comment by gsomoza** [comment]
Our extension adds practically no overhead to Magento, so the speed at which products load is directly proportional to the speed of your web server. I recommend you optimize or upgrade your Magento installation and you'll immediately notice the effects on the front-end.

If you're interested in optimizing your Magento installation but need help, please contact us at contact (at) strategery (dot) io - we're a team of Magento Certified Developers and expert sysadmins with many years of experience making Magento run.
