### ISSUE TITLE
I have a page with root category listing that I have done with cms page how to include infinite scroll in this

### ISSUE THREAD

**Issue by athulkvijayan** [Strategery-Inc/Magento-InfiniteScroll#144]
this is the design tab content
<reference name="left">
        
        <block type="catalog/layer_view" name="catalog.leftnav" template="catalog/layer/view.phtml" >
                <action method="setCategoryId"><category_id>3</category_id></action>
        </block>
</reference>

<reference name="content">
        <block type="catalog/product_list" name="home" template="catalog/product/list.phtml">

                
                <action method="setCategoryId"><category_id>3</category_id></action>
                <block type="catalog/product_list_toolbar" name="product_list_toolbar" template="catalog/product/list/toolbar.phtml">
                        <block type="page/html_pager" name="product_list_toolbar_pager"/>
                </block>
                <action method="setToolbarBlockName"><name>product_list_toolbar</name></action>

        </block>
</reference>

**Comment by gsomoza** [comment]
You should look at how IAS is configured on category pages and try to duplicate that in your CMS page. Unfortunately we can't help you further than that because what you're doing is out of the scope of this free plugin, so I'll close this ticket.
