### ISSUE TITLE
Error with Nginx

### ISSUE THREAD

**Issue by informundo** [Strategery-Inc/Magento-InfiniteScroll#151]
If used nginx to serve static content, in older browsers, infinity scroll automatically redirected to the next page without stopping, showing only the last. For example: http://www.mydomain.com/category, the automatically recharged http://www.mydomain.com/category?p=2, p = 3, p = 4 .... and show only the last in a single page (without above items). for example http://www.mydomain/category?p=10 with only the items of this page
Insight you the pagespeed Google also performs these redirects, giving error.

**Comment by janmyszkier** [comment]
@informundo! this is nginx configuration issue, rather than this plugin. Feel free to check this working on ubuntu virtual machine with nginx installed. The plugin itself doesn't REQUIRE anything beyond normal magento rewrite handling.

**Comment by gsomoza** [comment]
Thanks for chiming in Jan! @informundo does this issue happen on the demo using those old browsers? And if so: which browsers are you specifically referring to?

Closing this ticket for now because like Jan said this extension is not directly related to Nginx. We can continue the discussion though.
