### ISSUE TITLE
Scrolling Not working with product sorting

### ISSUE THREAD

**Issue by montybansal** [Strategery-Inc/Magento-InfiniteScroll#153]
I have used Strategery - InfiniteScroll plugin with Magento ver. 1.9.2.2, with ultimo theme its working on product listing page when scroll page down, but when I used either product sorting or sidebar filter then plugin not working on page scrolling. please help me in this problem

Thanks

**Comment by damian-pastorini** [comment]
Hi @montybansal , since this is not an issue in the extension itself but with your custom theme we can't provide free support.
If you like you can hire our development services so we can help you with the integration, for that you can contact us at contact (at) strategery (dot) io.

Best

**Comment by elfyrocks** [comment]
Whenever you want to add some custom layered navigation (ie. AheadWorks Layered Navigation or anything else that makes Ajax calls to update the product list or grid), just make sure to destroy the current IAS object and after that reinitialize SgyIAS by adding:
```
window.ias.destroy();
SgyIAS.init();
```
At the end of the function that calls the new content.
Cheers!

**Comment by damian-pastorini** [comment]
@elfyrocks , thanks for the notes!

**Comment by stefan68** [comment]
I think you can upgrade your site to Magento 2.x and then install this module for Magento 2 version: Infinite Scroll by BSS Commerce. It has been working well as described. 
Check it out here: http://bsscommerce.com/magento-infinite-scroll-for-magento-2.html

**Comment by gsomoza** [comment]
@stefan68 is that the most cost-effective solution you could come up with? LOL

You've been blocked for abusing our issue tracker, anyone interested can read the comment about it at #159

**Comment by gsomoza** [comment]
@elfyrocks excellent suggestion - @damian-pastorini could we move that suggestion to our extension's Wiki?

**Comment by damian-pastorini** [comment]
Notes included in "Development Notes" in the README file.
Thanks!
