### ISSUE TITLE
Show previous products when going back to catalog

### ISSUE THREAD

**Issue by rlaven** [Strategery-Inc/Magento-InfiniteScroll#156]
When you scroll down and for example click on a product on page 4. If you use the backbutton Magento is not showing the products on pages 1 / 2 / 3.  Is is possible to go back to page 4 but still be able to scroll up through pages 3 / 2 / 1?

Regards, 

Richard

**Comment by damian-pastorini** [comment]
Hi @rlaven , in our last version (assuming Magento 1), we enabled the back feature, so when you return with the back button to page 4 you will see the button to load previuos pages.
For reference you can check the old issue and the PR: 
https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/116

Best,

**Comment by informundo** [comment]
I updated to last version but don´t show the button to load previus pages. I test in default, rwd and custom template and don´t see in any.
In the configuration i test with selector "previous i-previous" and "previus".
Ej with default template: https://www.detiendas.online/informatica-y-oficina
Ej with custom template: https://www.navatiendas.es/informatica-y-oficina
Regards
![load previus](https://cloud.githubusercontent.com/assets/8274587/19566052/4161b9a4-96e9-11e6-9340-56c82028f339.png)

**Comment by damian-pastorini** [comment]
Hi @informundo , remember the selector is implemented with jQuery so it should be: 
`.previous.i-previous`
Because the link class:
![image](https://cloud.githubusercontent.com/assets/1211779/19578623/f4515548-96f2-11e6-952f-970364355137.png)

Please let me know how it goes.

Best,

**Comment by informundo** [comment]
Ok. Now work perfectly. Thanks.
