### ISSUE TITLE
Scroll both directions

### ISSUE THREAD

**Issue by cojaco** [Strategery-Inc/Magento-InfiniteScroll#158]
Hi,

is it possible to scroll also up? This would come in very handy when history back is enabled.

For excample a user scrolls through the product list klicks on a product, hits the back button, now its not possible anymore for the user to see products that he he has seen before in the same list.

He has to klick on the same Menu link again or has to alter the url (remove the ?p=x ), which is not so userfriendly.

**Comment by damian-pastorini** [comment]
Hi @cojaco , is not possible literally "scroll" back, but if you enable the back feature you should the "Load previous products" buttons for that matter.
We included the feature in this PR: https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/116
Best,

**Comment by cojaco** [comment]
Hi Damian,

yes I had the back feature enabled. there are two problems.
When it is enabled I can see ?p=2 in the url and I always jump back to this page.

But of course if I click than on a Product that is  P=1 (other pages can be in the viewport without changing the url) I can't go back to this product without click on the menu button or alter the url.

**Comment by damian-pastorini** [comment]
hi @cojaco can you tell me an URL where I can see the issue?
thanks!

**Comment by damian-pastorini** [comment]
@cojaco if you:
1 - scroll down until page 2 or 3
2 - access to a product
3 - then go back in the browser
4 - do you see the value for the page you were before right? like p=3
5 - at that point you should also see the "load previous items" button:
![image](https://cloud.githubusercontent.com/assets/1211779/16149908/4488bf60-346a-11e6-8add-51603889a5e4.png)
6 - if you click on that button the previous page should be loaded and the URL parameter should change to p=2 or p=1

**Comment by cojaco** [comment]
@damian-pastorini

thank you for your quick responses and patience, indeed I think I still use an older version of your module.
I don't have the previous button. That sounds very promising.

I'll try it next week.

**Comment by damian-pastorini** [comment]
@cojaco , great, just let us know how everything goes. If didn't have the extension last version that will probably fix everything.
Best,

**Comment by cojaco** [comment]
@damian-pastorini

yes that is what I was looking for!
First I forgot, that I had some overrides in my theme but now it works.

Thanks again!

**Comment by damian-pastorini** [comment]
Great!
Best,
