### ISSUE TITLE
List Mode Only Issue

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/Magento-InfiniteScroll#161]
Reported via Magento Connect (sic):

> I the List Mode Setting is Only List, the Module doesn´t work, because switch($defaultMode) in Row 68 of Init.php (Block) returns the default clause. So item in Row 76 of Init.phtml was set to grid and not list.
>
> You can solve the Bug if you change Row 76 of Init.php (Block) from
>
> $productListMode = 'grid';
> to
> $productListMode = $defaultMode;

**Comment by damian-pastorini** [comment]
This was already corrected:
https://github.com/Strategery-Inc/Magento-InfiniteScroll/blob/master/app/code/community/Strategery/Infinitescroll/Block/Init.php

**Comment by gsomoza** [comment]
Ah, he was probably using an older version of the extension then. Thanks Damian!
