### ISSUE TITLE
Not loading all products back.

### ISSUE THREAD

**Issue by ashishjob0424** [Strategery-Inc/Magento-InfiniteScroll#163]
It loads all product page wise when i am scrolling but issue produces suppose from page 3 i am clicking on any product to view the product details and then from detail page i am going back to list page from back button of browser then on listing page i am not able to load all my page.

**Comment by damian-pastorini** [comment]
Hi @ashishjob0424 , a few questions:
1 - Could you give a link where we can check the error? 
2 - Do you have a custom theme? 
3 - Did you installed InfiniteScroll last version?
4 - Did you tried the load previous products feature? Note: this is in the last InfiniteScroll version.

We need more information to check the issue please.

Best,

**Comment by damian-pastorini** [comment]
Hi @ashishjob0424 , any updates?
Thanks!

**Comment by damian-pastorini** [comment]
Without any updates, closing the issue.
