### ISSUE TITLE
Multiple selectors (Item: selectors)

### ISSUE THREAD

**Issue by ujwaldhakal** [Strategery-Inc/Magento-InfiniteScroll#166]
In the jquery option there is no option to pass multiple selectors for i.e to load the more than one div at a time different by id. For e.g in the jquery gridder like plugin it wont wok. Seriously neither there is no option to pass multiple param nor there is any option recall it

**Comment by damian-pastorini** [comment]
Hi @ujwaldhakal , could you clarify the issue for me please?
Why are you trying to use multiple selectors?
The selectors configuration are implemented in the IAS config and it requires unique selectors for each element.
The extension it self is not prepared to work with multiple InfiniteScroll instances in the same page if that's what you are looking for.

**Comment by ujwaldhakal** [comment]
I am trying to make it work on plugin like jQuery gridder as it wont work on it

-----Original Message-----

**Comment by damian-pastorini** [comment]
Hi @ujwaldhakal ,
Since this is a free extension and the issue is not related to the extension itself but with your custom implementation unfortunatelly we can't give you free support.
If you like you can hire our development services so we can assist you with the issue, just email us at contact@strategery.io.

Best,

**Comment by ujwaldhakal** [comment]
The extension wont work if we need the multiple selector in items param like currently we doing items:"selector" so it would be better if we could do items:"selector1,selector2 etc" or there is no any reboot method for the plugin

**Comment by ujwaldhakal** [comment]
I couldnt find the solution from there is there any thing you would
recommend on this?

**Comment by damian-pastorini** [comment]
At this point I don't really know why you need to use multiple selectors, maybe actually you need to create multiple InfiniteScroll instances in the same page, but the extension is prepared for that, so my recommendation is to hire a developer to customize the extension for your particular case.

Best,
