### ISSUE TITLE
Uncaught ReferenceError: $j is not defined

### ISSUE THREAD

**Issue by aurmil** [Strategery-Inc/Magento-InfiniteScroll#168]
hello
$j is defined in js/lib/jquery/noconflict.js which is loaded only in RWD theme
why not use jQuery at line $j(window).trigger('delayed-resize'); as in the rest of the file, instead of $j?
thanks

**Comment by gsomoza** [comment]
Definitely a good idea to use jQuery directly since it should always be available under that alias (if loaded).

If you can create a PR we'll happily merge it! 

Otherwise @damian-pastorini please deal with it when you get a chance.

**Comment by aurmil** [comment]
OK done, see https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/169

**Comment by damian-pastorini** [comment]
See the comments in https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/169 this only works with $j, we added a validation to avoid issues in other themes in: https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/170.

Best,
