### ISSUE TITLE
After implemented infinite scroll quick view not working

### ISSUE THREAD

**Issue by Vivendo** [Strategery-Inc/Magento-InfiniteScroll#171]
Hi team ,
After implemented infinite scroll quick view not working on next pages.Please see below quick view initialize code.

initialize: function(selector, x_image, settings)
    {
        Object.extend(this.settings, settings);
        this.createWindow();  
        
        var that = this;
        $$(selector).each(function(el, index){
            
        el.observe('click', that.loadInfo.bind(that));
      
        
        });
        $$(x_image).each(function(el, index){
            el.observe('mouseover', that.showButton);
            el.observe('mouseout', that.hideButton);
        });
        
    }

**Comment by gsomoza** [comment]
Please take a look at this: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page
