### ISSUE TITLE
mobile/tablet issue

### ISSUE THREAD

**Issue by geo782** [Strategery-Inc/Magento-InfiniteScroll#172]
Hi,
I just installed the infinitescroll with No include jquery in my 1.8.1 version with custom theme and the extensions works well except of the widths of the product grid and items. For example, after loading 2 more pages (total 3), the code for the first page is :
```
<ul id="grid" class="products-grid" style="width: 748px;">
<li class="item first_item_tm" style="width: 187px;">
<li class="item" style="width: 187px;">
<li class="item" style="width: 187px;">
```

And for the second page loaded and after, the code is : 
```
<ul id="grid" class="products-grid" style="display: block;">
<li class="item">
<li class="item">
<li class="item">
```

As you can see, the first page has widths but the rest (ul and li ) don't, so in tablet/mobile its broken.
There is no code in css files of theme for the widths, i checked files and if im correct, the theme is using js file for automatic widths. 
Is there any solution for this problem?

Regards
George

**Comment by gsomoza** [comment]
The best solution is to not use JS for adjusting widths; that's the root of the problem you're having. My recommendation would be to invest in migrating to a better responsive approach.

However if you want to "hotfix" this, it should be possible - you may want to look at [this page in the Wiki](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page) that explains how to run custom JS whenever a new set of results is loaded.

**Comment by geo782** [comment]
Hello, thanks for the reply. 
Unfortunately i dont undestand what code do i have to add. Theme is https://goo.gl/ZbkOha 
I have found a js file that I think that it is responsible for the column widths and the code in this file is : 
```
(function(a){a.fn.smartColumnsRows=function(b){var c=a.extend({defWidthClss:"grid_default_width",subElement:"li",subClass:"product-block",firstClass:"first_item_tm",lastClass:"last_item_tm"},b);
return this.each(function(){var f=a(this);
var k=a(this).attr("id");
var g=parseInt(a("."+c.defWidthClss).css("width"));
f.css("width","auto");
var j=f.width();
var i=g;
var d=Math.floor(j/i);
var e=g*100/Math.floor(j/d);
if(e<=75&&e>=50){d=d+1}if(a(window).width()<380){d=1}var h=Math.floor(j/d);
f.css("width",j);
a("#"+k+" > "+c.subElement).css("width",h);
a("#"+k+" > "+c.subElement).removeClass(c.firstClass);
a("#"+k+" > "+c.subElement+":nth-child("+d+"n+1)").addClass(c.firstClass);
a("#"+k+" > "+c.subElement).removeClass(c.lastClass);
a("#"+k+" > "+c.subElement+":nth-child("+d+"n)").addClass(c.lastClass);
f.waitForImages(function(){var l=0;
a("#"+k+" > "+c.subElement+" ."+c.subClass).each(function(){a(this).css("height","auto");
l=Math.max(l,a(this).height())});
if(l==0){l="auto"}else{l=l+"px"}a("#"+k+" > "+c.subElement+" ."+c.subClass).css("height",l)})})}}(jQuery));
```

How do I run this code everytime a new page is loading? I have "Include jQuery" set to "No" in settings.

Regards
George

**Comment by gsomoza** [comment]
Unfortunately, since this is a free extension, we can't provide free support for things that are not a bug on the extension. This is a specific problem with your current theme or a customization that was applied to it. I recommend you hire a qualified Magento developer to help you fix it.

If you're interested in hiring one of my company's developers feel free to send me an email at: contact (at) strategery (dot) io

**Comment by geo782** [comment]
Please check your email.

**Comment by geo782** [comment]
I managed to solve the problem by editing the init.phtml at /app/design/frontend/default/CUSTOMTHEME/template/strategery/infinitescroll/
I added 3 lines
```
$(document).ready(productListAutoSet);
$(window).bind('resize', productListAutoSet);
console.log('Product Grid Resize Done!');
```

before the });

in
```
window.ias.on('rendered', function(items){
SgyIAS._log({eventName: 'render', items: items});
if (typeof $j !== 'undefined' && !!$j) {
$j(window).trigger('delayed-resize');
};
});
```

**Comment by gsomoza** [comment]
Great, and thanks for posting the solution so others can benefit!
