### ISSUE TITLE
Previous page not working

### ISSUE THREAD

**Issue by systechabc** [Strategery-Inc/Magento-InfiniteScroll#174]
Hello,

I was looking for the "Show previous page" functionality when the user clicks on a product and then decides to click on the "Back" button. I see that You state that this functionality works, but it does not seem to be working for me. I have downloaded the latest version, and I see the part of the code which should be responsible for kicking this process into action, but it does not seem to work for me.
I believe that these lines should be highlighted from the config variable:
history: {
                                prev: '<?php echo $helper->getConfigData('selectors/previous') ?>'
                            },
which compiles to
 history: {
                                prev: '.previous'
                            },

and these:
 trigger: {
                                text: '<?php echo $helper->jsQuoteEscape($this->__($helper->getConfigData('design/load_more_text'))) ?>',
                                html: '<div class="ias-trigger ias-trigger-next" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                                textPrev: '<?php echo $helper->jsQuoteEscape($this->__($helper->getConfigData('design/load_more_text_prev'))) ?>',
                                htmlPrev: '<div class="ias-trigger ias-trigger-prev" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                                offset: <?php echo (int) $helper->getConfigData('design/load_more_threshold') ?>
                            }

which compile to:
 trigger: {
                                text: '',
                                html: '<div class="ias-trigger ias-trigger-next" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                                textPrev: 'Load previous items',
                                htmlPrev: '<div class="ias-trigger ias-trigger-prev" style="text-align: center; cursor: pointer;"><a>{text}</a></div>',
                                offset: 5                            }
                        };

However, I do believe that the htmlPrev should be using "textPrev" inside its <a> html tag, but this is Your code originally. I have also tried using it with {textPrev}, but nothing happened...

Am I doing something wrong?

Best regards and thanks in advance,

**Comment by systechabc** [comment]
If it is relevant, my Magento version is 1.9.2.1.

**Comment by damian-pastorini** [comment]
Hi @systechabc , 

A few questions:
- Do you have a custom theme? Maybe you just need to change the previous button selector? 
- Did you flushed cache? 
- Could you tell me an URL where I can see the issue?
- Did you tried to enable the IS debug mode to see if there's any issue in the console?

Best,

**Comment by systechabc** [comment]
Hello Damian,

I do have a custom theme.
I have tried setting the previous button selector to .prev and to .previous, but neither worked.
I have tried flushing the cache, but it still did not work.
You can see this on this link http://bilablaudevelop.com/sunglasses.html
The debug mode is enabled and it is logging stuff in the console but I would need to get deep inside the code itself to see what is wrong. I thought that You could help me as You wrote the plugin and have much much more experience with it.

Best regards,

**Comment by systechabc** [comment]
It doesn't matter anymore, we managed to solve it ourselves.
Best regards.

**Comment by damian-pastorini** [comment]
Hi @systechabc , sorry I didn't have time to check on the issue, how did you fix it?

Best,
