### ISSUE TITLE
Magento 1.9 strategery infinite scroll not working

### ISSUE THREAD

**Issue by ramesh8391** [Strategery-Inc/Magento-InfiniteScroll#178]
Am using Magento 1.9 theme coolbaby. i'm configure every thing 
![m1](https://cloud.githubusercontent.com/assets/28915958/26388153/41f4641c-4070-11e7-9604-76e0bca4d0ba.JPG)

but i got some error in console and also product not loaded 
![m2](https://cloud.githubusercontent.com/assets/28915958/26388181/718478de-4070-11e7-9f96-c8496d586a73.JPG)

error in http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js file 

How can i fix this..?

Thanks,
Ramesh S

**Comment by gsomoza** [comment]
Looks like you have an invasive AJAX extension installed, please check [this article](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts) in the wiki for more help.

**Comment by ramesh8391** [comment]
Hi gsomoza,

Thanks for your reply. you are right,  am using Ajax cart in my theme. If am omit Ajax cart this extensions will working or not...?

**Comment by gsomoza** [comment]
Probably yes (or at least you won't get this same error) - try disabling that extension temporarily to confirm.

**Comment by ramesh8391** [comment]
Yes this is the error i got in console 

"_Uncaught Error: Syntax error, unrecognized expression: {"status":"SUCCESS","viewpanel":"\n\n\n\n<div class=\"block block-layered-nav\">\n\n    <div class=\"block-content\">\n\n ect....._"
