### ISSUE TITLE
Demo isn't working

### ISSUE THREAD

**Issue by scottmberry** [Strategery-Inc/Magento-InfiniteScroll#179]
I haven't tried to install myself. But your demo doesn't seem to be working right. Nothing loads automatically, there is a "load more" text link under the first page. If I click that a broken image shows, the text still shows and eventually the next page loads below. The text still exists in between the two pages and then nothing else loads after I scroll down past page 2.

**Comment by gsomoza** [comment]
Thanks for reporting! Indeed - we indeed have to fix the demo, but to be honest it's likely we'll just take it down altogether, since most versions of Magento 1 are losing official support soon anyways.

**Comment by scottmberry** [comment]
Keep it up! Lots of people still use M1 and won't be converting any time soon.

**Comment by gsomoza** [comment]
You're right, Magento officially announced continued support. We'll look into it as soon as possible.

**Comment by damian-pastorini** [comment]
Demo is back online: http://demo.usestrategery.com/infinite-scroll/infinitescroll.html
