### ISSUE TITLE
InfinteScroll || Not Working

### ISSUE THREAD

**Issue by jiteshmalhotra** [Strategery-Inc/Magento-InfiniteScroll#180]
Hi,
I have installed an infinite scroll - Strategery. I have kept all the files at there respective paths or folder. But It is not working, I have enabled from backend too. 
Kindly help to resolve this issue out.

Thanks,
Jitesh

**Comment by gsomoza** [comment]
Have you been able to check the [Wiki](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki) for common issues?
