### ISSUE TITLE
Infinite Scroll not working

### ISSUE THREAD

**Issue by udupi** [Strategery-Inc/Magento-InfiniteScroll#181]
Hi sir,
         I'm facing issues with infinite scrolling. 
My Magento version is 1.9.2.4 and have installed venusthemes.
I have installed the extension using https://connect20.magentocommerce.com/some_key/strategery+Strategery_InfiniteScroll2-3.5.3 in Magento Connect Manager and followed instructions as per the installation procedure. 

Selectors are same as one which is default in the selectors tab under configuration. I saved the configuration settings and cleared the site cache and browser cache and checked. Unfortunately it didn't work. Still showing default numbered pagination. Even crosschecked the files structure with zip file downloaded from Magento market place. Files are at the required positions. 
Then I followed the below link
https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Installation-under-a-different-package---theme 

Except First 2 points, rest were meeting my configurations. Below are the images  which can give you idea about my problem.
![inspect](https://user-images.githubusercontent.com/15322175/28420338-77040c3e-6d7f-11e7-8fba-a006080b53a9.png)

![page source-1](https://user-images.githubusercontent.com/15322175/28420353-802172c0-6d7f-11e7-8e01-4c402cef6a83.png)

Can you give me complete path mentioned in 1st point. I didn't find any file with name package/theme inside front end. 
About 2nd point, example.com/infinitescroll2/js link showed me 404 error. 
Can you please help me and since 2 days i'm working on it. No progress.

Note: No 3rd party extensions are installed that is mentioned in the [wiki](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/3rd-party-Extension-Conflicts)

Thank You

**Comment by gsomoza** [comment]
The 1st point shouldn't be necessary anymore because the files are being distributed inside `app/design/frontend/base/default`, which is the final fallback for most themes. I updated the documentation accordingly.

Seems like your only problem might be that 404. Could you find that file in the filesystem? `{magento-root}/js/jquery/infinitescroll/jquery-ias.min.js`

**Comment by gsomoza** [comment]
Is this path also giving you a 404: `skin/frontend/base/default/js/infinitescroll/ias_config.js`?

**Comment by udupi** [comment]
Hi sir,
      I'm glad that you replied. Coming to the point, the file which you mentioned in the 1st reply:
**Seems like your only problem might be that 404. Could you find that file in the filesystem? {magento-root}/js/jquery/infinitescroll/jquery-ias.min.js** 

The file is present. I've cross checked it.

About your second reply:
**Is this path also giving you a 404: skin/frontend/base/default/js/infinitescroll/ias_config.js?**
This path is returning me

```
window.ias_config = {
    // options from https://github.com/webcreate/infinite-ajax-scroll
};
/* IS Custom Event to Hook into */
/*
 jQuery(document).on('infiniteScrollReady',function(){
    console.log('bam!');
});
*/
```
seems like commented out. Can you please tell me what am I missing. 

Thanks, Pal.

**Comment by gsomoza** [comment]
The second file is OK then.

If the first file is present in your filesystem and in the correct location, but the web server is returning a 404, then there might be a problem with your web server configuration. Are other files inside `{magento-root}/js/*` being served properly?

**Comment by udupi** [comment]
Hi Sir,
The file is inside the file system you mentioned. And even the **js/jquery/infinitescroll/jquery-ias.min.js** path is rendering the js contents in the browser. So I feel there may not be an issue with the file structure as I used the extension link from magento marketplace. Do you get any other possible issues in your mind? 
![config](https://user-images.githubusercontent.com/15322175/28460505-f9ed7f80-6e2f-11e7-951d-34c4480bcbaa.png)
![config-1](https://user-images.githubusercontent.com/15322175/28460509-fd1c33f4-6e2f-11e7-9789-6587eaed9671.png)

Here is my configuration settings page snap. Please help me out.

Thanks, Pal

**Comment by udupi** [comment]
Hi sir,
        Did you get any idea regarding the issue? Can you please help me in tracing the issue. 

Thank You

**Comment by gsomoza** [comment]
Are you still getting those 404s? I'd check the server until you find the root cause for that 404.

**Comment by udupi** [comment]
Hi sir,
          Happy to see you back and once again thank you for replying. Sir let me tell you that none of the links mentioned in your replies have 404 error. I've cross checked the same several times. I'm not understanding how to trace the issue as even the **view source** page shows me all infinite scroll js contents. **404 is not there**

Please do look into the screenshots
1) pagination preview:
![pagination](https://user-images.githubusercontent.com/15322175/28764156-223e37dc-75e1-11e7-9ef8-05c1b2239b12.png)

2)jquery-ias.min.js  ( js/jquery/infinitescroll/jquery-ias.min.js)
![jquery-ias_min_js](https://user-images.githubusercontent.com/15322175/28764189-6589b502-75e1-11e7-9bf3-e0fb3fc0d84f.png)

**Comment by gsomoza** [comment]
Do you have the site online somewhere we can see it? Otherwise I'm afraid we won't be able to help.

I also wanted to take the opportunity to just mention that we only offer support for bug fixes on our extension. If you're having integration issues (e.g. related to the custom theme) then we won't be able to help much because this is a free extension. If you want commercial support you can email us at contact (at) strategery (dot) io

**Comment by PawanKumarN** [comment]
i have installed extension after installing i check the below link
 http://www.mysite.com/infinitescroll2/js but i got 404 i am struggling from 2 days please guid me how to resolve

**Comment by damian-pastorini** [comment]
hi @PawanKumarN , 
- Do you still have the issue? 
- If so could you provide an URL where we can check it?
- Do you have any theme or customization implemented in the frontend?
Best,

**Comment by damian-pastorini** [comment]
So far I'm not able to reproduce the any of the commented issues in a default Magento installation.
