### ISSUE TITLE
Ultimo + Price

### ISSUE THREAD

**Issue by bakkee** [Strategery-Inc/Magento-InfiniteScroll#182]
Hi,

I got issue with ultimo template, prices are not appears when load new page.
Any idea what that can be?

**Comment by gsomoza** [comment]
Please refer to this document in the Wiki: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Functionality-Issues-After-Loading-Next-Page

**Comment by bakkee** [comment]
Sorry im newbie in this. But should i install ajax scroll?
