### ISSUE TITLE
Not working under https

### ISSUE THREAD

**Issue by danielchicote** [Strategery-Inc/Magento-InfiniteScroll#184]
Hello seems that the module does not work under ssl. I'm the only one?

**Comment by damian-pastorini** [comment]
Hi @danielchicote , could you provide an URL where we can check the issue?
Another considerations will be: 
- Do you have any customizations implemented?
- Any other information like Magento version, environment, etc. will help.
Thanks!

**Comment by danielchicote** [comment]
Hi I have found the cause. It was the url of one image of the skin, that was non https.
Now its working. :)
