### ISSUE TITLE
Show Button for loading

### ISSUE THREAD

**Issue by kaushalsutharhs** [Strategery-Inc/Magento-InfiniteScroll#185]
Instead of loading product automatically, How can we display "Load more" button and on click we load more product?

**Comment by damian-pastorini** [comment]
Hi @kaushalsutharhs , you can set the "Load More threshold" option to zero, it's located in:
System / Configuration / InfiniteScroll / Design
Best,

**Comment by kaushalsutharhs** [comment]
@damian-pastorini : thanks :+1:
