### ISSUE TITLE
Extension Conflict (404 - "Error", "End") 

### ISSUE THREAD

**Issue by ghost** [Strategery-Inc/Magento-InfiniteScroll#35]
Hi all.

I'm having some problems to get this Extension to work. I'm using it on a Magento Multistore System (1.7.0.2). When I browse a category, InfiniteScroll seems to work but the extension doesn't load any new products. The loading block appears and then returns a "...you've reached the end of the internet" notification. 

Following information are logged in my console: 

GET http://www.mydomain.de/category/where/p/2.html&scrollCall=1 404 (Not Found) jquery-1.7.2.min.js:4
["Error", "end"] jquery.infinitescroll.js:182
["Binding", "unbind"] 

FYI - We are using "SEO Layered Navigation Plus" from ManaDev. When I deactivate this extension, everything works PERFECTLY.

Is there a known conflict? Any help would be appreciated! 
Chris

**Comment by rahulsode** [comment]
Hi,
I had the same issue, needed to edit CategoryController.php and ResultController.php in Sm Shop by extension, after doing that my java-script error is gone, and when scroll down to bottom the page no. in the url is changed but the next content is not appended to the main list ...
Any Solutions or Idea, what could be the reason??

**Comment by gabrielsomoza** [comment]
Does this help? https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Nothing-Happens,-Although-the-%22Loading-Next-Page%22-Message-is-Visible

**Comment by rahulsode** [comment]
Got the solution!!!
turns out My theme Sm Love Fashion Provides me module called "Sm Shop by" which uses Ajax to filter the products collection according to the selected criteria, i don't know some how this was conflicting with  Magento-InfiniteScroll, once i removed that sm shopby module, everything works fine...
thanks for the help..

**Comment by gabrielsomoza** [comment]
Yes, usually extensions like that one mess up with all AJAX requests made to Magento in a way that's very obtrusive and completely unnecessary.

**Comment by jasonalvis** [comment]
Did anyone manage to get this working with the SEO Layered Navigation Plus module, so far I have this but doesn't appear to be working:

$(document).bind("m-ajax-after", function(e, selectors, url, action){
    $.ias().unbind();
    $.ias().initialize();
});
