### ISSUE TITLE
Loading the same products continuously

### ISSUE THREAD

**Issue by patricksteenks** [Strategery-Inc/Magento-InfiniteScroll#63]
I have installed the plugin through Magento Connect and everything is working ok. However, when new products are loaded on a page, it keeps on loading the same two products.

See for an example: http://www.slankenlijn.nl/onder-begeleiding. On scroll it keeps onloading the same two products.

If I go to the last page it is working correctly.

**Comment by mansidhaduk** [comment]
I have also installed the plugin through Magento Connect but i am also facing this same problem I have already apply all possible solution but it is not working..Please anybody can help me???
