### ISSUE TITLE
Not working with custom theme

### ISSUE THREAD

**Issue by jpmarin** [Strategery-Inc/Magento-InfiniteScroll#71]
Hi I included the extension in www.frommuranowithlove.com but could not make it work

I did copy all files in app/design to my theme folder 
from
app/design/frontend/default/default/template
to
app/design/frontend/ultimo/default/template

and, just in case, file in skin/frontend to my theme folder also
from
skin/frontend/base/default/
to
skin/frontned/ultimo/default/

I read all the article in the wiki about custom themes but get stuck in step 2 since I get a 404 page and I do not know how to fix it.

Could you please help?

Thanks!

**Comment by anurag-do** [comment]
also prices are not coming on grid when hover on products  http://www.frommuranowithlove.com/murano-chandeliers.html#/page/2

**Comment by damian-pastorini** [comment]
That's a custom theme and it looks that the hover effect is been applied by JS:
`$('.category-products-grid > .item').hover(function() { ...`
so you will need to create an observer for the infinitescroll event to re-apply the hover effect on the items loaded by the scroll.

Best,

**Comment by anurag-do** [comment]
how to apply that ?

**Comment by damian-pastorini** [comment]
@anurag-do you will need to add some custom code in your website, something like:
```
jQuery(document).on( "infiniteScrollReady", function(){
	console.log('test observer');
	jQuery('.category-products-grid > .item').hover(function() {
		console.log('hover effect code');
	});
});
```

**Comment by damian-pastorini** [comment]
@jpmarin , are you still having the issue? Where** did you get the 404? In the System / Configuration page? That's usually because you need to logout and login again to the admin so the ACL is reloaded for your admin user.

Best,
Damian

**Comment by anurag-do** [comment]
thanks @damian-pastorini  :)

**Comment by gsomoza** [comment]
Closing this ticket for now because its an theme-specific issue (the discussion can continue anyway even when closed).
