### ISSUE TITLE
Loading same page continuously

### ISSUE THREAD

**Issue by skidrow91** [Strategery-Inc/Magento-InfiniteScroll#73]
I'm using plugin and have a problem, that is after first loading, second loading get correct products in category, and third loading, it should loading page 3 but it loading again page 2.
Is it bug of plugin or i config not correct?

Link: http://demo.usestrategery.com/infinite-scroll/electronics/all-products.html

**Comment by gabrielsomoza** [comment]
Looks like we had a bug in our demo rather than the plugin. This doesn't seem to be a problem when the extension is correctly configured in Magento's demo store. Take a look at the updated demo: http://demo.usestrategery.com/infinite-scroll/infinitescroll.html
