### ISSUE TITLE
Syntax Error with custom theme

### ISSUE THREAD

**Issue by siddharth-vaghasia** [Strategery-Inc/Magento-InfiniteScroll#85]
Hi, I am getting below error after integrating with custom theme

Page is loading correctly intialilng, when I scroll down page url changes to 
http://localhost/mysite/index.php/mens/jeans.html?p=2 
after sometime front end says ' Loading the next set of posts...'
but give below javascript error 

ERROR DETAILS.....it is long string like html....
Uncaught Error: Syntax error, unrecognized expression: {"listing":"\n    <div class=\"category-products\">\n\t\t<div class=\"toolbar-top\">\n        <div class=\"toolbar\">\r\n\t<div class=\"toolbar-inner\">\r\n.....................

Have checked steps mentioned steps in below url , seems to be correct other than i am not able to browser js
https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Installation-under-a-different-package---theme
'
Only doubt I have is 4 js files under \js\jquery\infinitescroll seems to be not loading, where do I have to include this js file so that it is loaded.

or anything else I am missing.
Thanks
Siddharth

**Comment by rahulsode** [comment]
@siddharth-vaghasia Hi, I am getting the same error, I tried hard but couldn't solve, can you tell what was you solution??

**Comment by gabrielsomoza** [comment]
The issue was probably related to a 3rd-party extension that incorrectly modifies Magento's response to AJAX requests. See this article for more guidance: https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Nothing-Happens,-Although-the-%22Loading-Next-Page%22-Message-is-Visible

**Comment by sunny29mca** [comment]
Hi, I am getting below error after integrating with custom theme when extention enabled

Page is loading correctly intialilng, when I scroll down page url changes to
http://localhost/mysite/index.php/mens/jeans.html?p=2
after sometime front end says ' Loading the next set of posts...'
but give below javascript error

ERROR DETAILS.....it is long string like html....
Uncaught Error: Syntax error, unrecognized expression: {"listing":"\n

**Comment by sunny29mca** [comment]
i am using magento 1.9

**Comment by gabrielsomoza** [comment]
@sunny29mca your issue is related to an extension that unfortunately transforms all AJAX requests to Magento. Its a bad practice. More info in our Wiki, check [this article](https://github.com/Strategery-Inc/Magento-InfiniteScroll/wiki/Nothing-Happens,-Although-the-%22Loading-Next-Page%22-Message-is-Visible)

**Comment by sunny29mca** [comment]
so what to do?

**Comment by sunny29mca** [comment]
I have not "Aheadworks Ajax Cart Pro" ext

**Comment by gabrielsomoza** [comment]
You may have another extension that causes that error to happen when our extension is enabled (maybe for layered navigation, but it could be anything really). I'm afraid this is an integration that only a PHP developer can help you with.
