### ISSUE TITLE
Scrolling is not working perfectly

### ISSUE THREAD

**Issue by vinitchopra** [Strategery-Inc/Magento-InfiniteScroll#90]
I found a bug that in this extension. When you scroll all product and then if you apply any navigation filter like Price, color etc. then the extension is not working at all. 

Could you please investigate the issue and help me out to fix this issue.

**Comment by gabrielsomoza** [comment]
@damian-pastorini could you verify if this is a bug?

**Comment by damian-pastorini** [comment]
I recently did a test and it works fine with the default RWD theme.
I open a category, scrolled to the end, applied a filter (price in my case), and the scroll keep working normally.

@vinitchopra , do you have a link were we could take a look on the issue? Do you have a custom theme or 3rd party layer navigation extension implemented?

**Comment by antoniocarboni** [comment]
i verify the problem only when the browser's cache is active

**Comment by damian-pastorini** [comment]
@antoniocarboni , do you mean some browser speed boster, something like an "extra plugin for cache" or just the simple browser cache?
Wich browser are you using?
Because I never clean up the browser cache for the tests and everything is still working fine.

**Comment by damian-pastorini** [comment]
@antoniocarboni any updates on this?
