### ISSUE TITLE
Problem js

### ISSUE THREAD

**Issue by vladeight** [Strategery-Inc/Magento-InfiniteScroll#92]
Error: Syntax error, unrecognized expression: {"status":"SUCCESS","viewpanel":"<div class=\"block block-layered-nav\">\n ...
What seams to be the problem? Ive try to change the js from my custom theme but the problem persiste.Can you give me some directions ?
I think what I see that ajax call the right column were in my case is the future products ,shop by ... .
This is the html response :
{"status":"SUCCESS","viewpanel":"
\n
\n Shop By<\/span><\/strong>\n <\/div>\n
\n
\n
\n
\n
\n
\n Price Filter <\/div>\n <\/div>\n <\/div>\n
\n
\n
\r\n Price<\/label>\r\n\t\t\t\t
\r\n\t\t\t\t\t

\r\n\t\t\t\t\t\r\n\t\t\t\t\t<\/p>\r\n\t\t\t\t\t
<\/div>\r\n\t\t\t\t\t\r\n\t\t\t\t<\/div><\/div>\r\n\t\t\t

**Comment by gabrielsomoza** [comment]
We don't return that kind of output in our extension, so this definitely doesn't look like a problem on our end..

You probably have some other extension that's changing the output of AJAX requests made to the server. Maybe AjaxCartPro or something like that - they're known to be problematic and poorly architected.

If you need commercial help integrating our extension or fixing this other extension let me know.
