### ISSUE TITLE
not working with 1.9.1 configurable swatches - image change

### ISSUE THREAD

**Issue by mattyl** [Strategery-Inc/Magento-InfiniteScroll#95]
trying to work out how to initialise the swatches on render

this is the js code necessary and is generated

<script type="text/javascript">
    jQuery(document).on('product-media-loaded', function() {
        ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
        <?php foreach ($this->getProductImageFallbacks() as $imageFallback): ?>
        ConfigurableMediaImages.setImageFallback(<?php echo $imageFallback['product']->getId(); ?>, $j.parseJSON('<?php echo $imageFallback['image_fallback']; ?>'));
        <?php endforeach; ?>
        jQuery(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
    });
</script>
have tried this

						window.ias.on('rendered', function(items){
							SgyIAS._log({eventName: 'render', items: items});
							alert('cf');
        					jQuery(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
						});

but thats not working

**Comment by mattyl** [comment]
so remove script tags here is js code
 jQuery(document).on('product-media-loaded', function() {
        ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
        <?php foreach ($this->getProductImageFallbacks() as $imageFallback): ?>
        ConfigurableMediaImages.setImageFallback(<?php echo $imageFallback['product']->getId(); ?>, $j.parseJSON('<?php echo $imageFallback['image_fallback']; ?>'));
        <?php endforeach; ?>
        jQuery(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
    });

**Comment by mattyl** [comment]
heres a test url
http://azuni.smbsolutionsuk.net/collections/athena?p=8
the three stone bangless works as expected
scroll up - the window cut stone necklace doesnt

**Comment by gabrielsomoza** [comment]
@damian-pastorini could you take a look at this when you get the chance?

**Comment by damian-pastorini** [comment]
Confirmed there's an issue in the extension: the swatches don't change the image when the product is loaded by the InfiniteScroll.

@mattyl thanks for report the issue, I will work on it as soon I can but if you found a fix before that please feel free to modify the extension files and create a PR so we could include it in the project. Thanks again!

**Comment by mattyl** [comment]
Ok if i solve it will let you know!

**Comment by RDXSportsCom** [comment]
Can anyone tell me if you fix it, i am using it with Magento Enterprise Edition, but not swatches not working... ?

**Comment by janmyszkier** [comment]
let me check on this, will be back with details in few hours max

**Comment by RDXSportsCom** [comment]
sure, i am waiting for your feedback.

**Comment by janmyszkier** [comment]
@mattyl, @RDXSportsCom:
posting a workaround for those who has to have it at all cost "NOW", but I highly advise waiting for official fix:

in app/design/frontend/rwd/default/template/catalog/product/list.phtml, line 169, just above 
```php
</li>
            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
        <?php endforeach ?>
    </ul>
```

Add following lines
```php
<?php
                /* WORKAROUND START */
                /**
                 * WARNING: this is workaround!!!!
                 * See here for more details: https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/95
                 *
                 */
                $csmfHelper = Mage::helper('configurableswatches/mediafallback');
                $swatchImageFallback = $csmfHelper->getConfigurableImagesFallbackArray($_product, array('small_image'), true);
                ?>
                <script type="text/javascript">
                    ConfigurableMediaImages.setImageFallback(<?php echo $_product->getId(); ?>, jQuery.parseJSON('<?php echo Mage::helper('core')->jsonEncode($swatchImageFallback); ?>'));
                    ConfigurableSwatchesList.init();
                </script>
                <?php
                /* WORKAROUND STOP */
                ?>
```

make note however, this adds more than it should, I'm working on refactoring this this now when I have it working

**Comment by RDXSportsCom** [comment]
:) thanx for fixing my issue :+1: its working fine for me in Magento Enterprise Edition, for now i use with your fixed code, but i will replace extension as soon as you officially release it.

**Comment by zeki893** [comment]
@janmyszkier nice that works. If anybody is using it with 
[AjaxSwatches](https://github.com/wigman/AjaxSwatches)

    <script>
        ConfigurableMediaImages.ajaxLoadSwatchList();
    </script>

Add that inbetween

    <?php endforeach ?>
        <script>
            ConfigurableMediaImages.ajaxLoadSwatchList();
        </script>
    </ul>

**Comment by damian-pastorini** [comment]
@gsomoza I just created this PR for the fix: https://github.com/Strategery-Inc/Magento-InfiniteScroll/pull/148
Please take a second look on it so we can merge it.
Thanks!

**Comment by damian-pastorini** [comment]
Merged PR, closing issue.

**Comment by vishy93** [comment]
https://github.com/Strategery-Inc/Magento-InfiniteScroll/issues/200
